### ISSUE TITLE
Error when creating account

### ISSUE THREAD

**Issue by TOBIBLASTER00912** [rzc0d3r/BitdefenderGen#2]
It says "invalid page"
![image](https://github.com/user-attachments/assets/7aeffe0c-1f72-4da3-b1b2-b5d2db955b90)

**Comment by rzc0d3r** [comment]
Use another email api

**Comment by TOBIBLASTER00912** [comment]
its still wont work
![image](https://github.com/user-attachments/assets/204296e9-399d-4390-aa95-5ea432f0ff33)

**Comment by rzc0d3r** [comment]
I need to look for suitable addresses, and the site is really nasty

**Comment by rzc0d3r** [comment]
This page has been disabled
